language: node_js
node_js:
  - "9"
env:
  - CXX=g++-4.8
install:
  - npm i
script:
  - npm run build
cache:
  directories:
    - node_modules
notifications:
  # email: false
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: out
  github-token: $GITHUB_TOKEN
  repo: lunelson/travis-build-test
  keep-history: true
  target-branch: master
  on:
    branch: master
