language: node_js
node_js:
  - "9"
install:
  - npm i
script:
  - npm run build
cache:
  # directories:
  #   - node_modules
notifications:
  # email: false
deploy:
  repo: lunelson/travis-build-test
  provider: pages
  skip-cleanup: true
  local_dir: out
  github-token: $GH_TOKEN
  keep-history: true
  fqdn: lunelson.de
  # target-branch: gh-pages
  on:
    branch: master
